### ISSUE TITLE
Multiline view

### ISSUE THREAD

**Issue by Sash0k** [aids61517/EasyRatingView#1]
Can you add feature to add second (and more) line for a view?
For example, not enough space for 9 stars.

![device-2020-09-21-160543](https://user-images.githubusercontent.com/1607158/93770254-9fe79d00-fc24-11ea-90c3-cc3ba410d362.png)

But it will be ok with second line
![Снимок экрана_2020-09-21_16-01-43](https://user-images.githubusercontent.com/1607158/93770587-0cfb3280-fc25-11ea-8e49-854334d2e12f.png)

**Comment by aids61517** [comment]
Sorry for the late reply, I didn't see this issue until yesterday...
I release 1.1.0 to support multiline when space is not enough, and thanks this feature request

**Comment by Sash0k** [comment]
thanks!
i've workarounded this with vertical linearlayout and two EasyRatingViews. 
Will try a new version bit later

**Comment by Sash0k** [comment]
tested it. Awesome, thanks!
